version: '2.1'
services:
  ttb-backend:
    image: mrosetti/time-tracking-bot-backend:dev
    container_name: ttb-backend
    restart: unless-stopped
    environment:
      - FB_PAGE_TOKEN=${FB_PAGE_TOKEN}
      - FB_VERIFY_TOKEN=${FB_VERIFY_TOKEN}
      - FB_APP_SECRET=${FB_APP_SECRET}
      - FB_PORT=3500
      - REDMINE_HOST=http://redmine:3000
      - REDMINE_API_KEY=48af6895688ca2108cafed19fed5bffafc541eea

  agendash:
    image: lgatica/docker-agendash
    container_name: agendash
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://mongo/agenda
    ports:
      - 4000:3000

  redmine:
    image: redmine:3.4.2
    container_name: redmine
    restart: unless-stopped
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_PASSWORD: example
    ports:
      - 3000:3000
    volumes:
      - redmine-files:/usr/src/redmine/files

  redminedb:
    image: mysql:5.7
    restart: unless-stopped
    container_name: redmine-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - redmine-mysql-files:/var/lib/mysql

  mongo:
    image: mongo:3.4.7
    container_name: mongo
    command: --smallfiles --setParameter failIndexKeyTooLong=false
    restart: unless-stopped
    volumes:
      - mongo-dbdata:/data/db
      - mongo-configdata:/data/configdb
    logging:
      driver: json-file
      options:
        max-size: "512m"
        max-file: "3"

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "512m"
        max-file: "3"
    ports:
      - 80:80
      - 443:443
      - 27017:27017
    volumes:
      - nginx-conf:/etc/nginx
      - ssl-certs:/etc/letsencrypt

volumes:
  redmine-files:
    external: true
  redmine-mysql-files:
    external: true
  mongo-dbdata:
    external: true
  mongo-configdata:
    external: true
  nginx-conf:
    external: true
  ssl-certs:
    external: true
