version: '2.1'
services:
  parse-server:
    image: mrosetti/time-tracking-bot-backend
    container_name: ttb-backend
    restart: unless-stopped
    environment:
      - FB_PAGE_TOKEN=EAAZAVZCxbZAULwBAChclH5RHHyCsQZAYTEfzPOEZAyWvhlLCEJGSFB91thV0FIHg6DqZAAT0vyrwk8tPQFRoOva69eZAG5cDyUhHc5ZCrrXV9C03qOrZA05DyZAcKs6evt2fK4pxIsGHgJclLOiiqnck5g8iue3rKTGkWRR0ZA0XlxJbAZDZD
      - FB_VERIFY_TOKEN=mysecret
      - FB_APP_SECRET=8e6d7944e4a95b4e2b19a0b60b6ec6db
      - FB_PORT=3500
    ports:
      - 3500:3500

  parse-dashboard:
    image: redmine
    container_name: ttb-redmine
    restart: unless-stopped
    ports:
      - 3000:3000

  mongo:
    image: mongo:3.4.7
    container_name: ttb-mongo
    command: --smallfiles --setParameter failIndexKeyTooLong=false
    restart: unless-stopped
    ports:
     - 27017:27017