version: '2.1'
services:
  # ttb-backend:
  #   image: mrosetti/time-tracking-bot-backend:dev
  #   container_name: ttb-backend
  #   restart: unless-stopped
  #   environment:
  #     - FB_PAGE_TOKEN=EAAZAVZCxbZAULwBAChclH5RHHyCsQZAYTEfzPOEZAyWvhlLCEJGSFB91thV0FIHg6DqZAAT0vyrwk8tPQFRoOva69eZAG5cDyUhHc5ZCrrXV9C03qOrZA05DyZAcKs6evt2fK4pxIsGHgJclLOiiqnck5g8iue3rKTGkWRR0ZA0XlxJbAZDZD
  #     - FB_VERIFY_TOKEN=mysecret
  #     - FB_APP_SECRET=8e6d7944e4a95b4e2b19a0b60b6ec6db
  #     - FB_PORT=3500
  #     - MONGO_HOST=ttb-mongo
  #     - MONGO_PORT=27017
  #   ports:
  #     - 3500:3500

  agendash:
    image: lgatica/docker-agendash
    container_name: agendash
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://mongo/agenda

  redmine:
    image: redmine:3.4.2
    container_name: redmine
    restart: unless-stopped
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_PASSWORD: example
    volumes:
      - redmine-files:/usr/src/redmine/files

  redminedb:
    image: mysql:5.7
    restart: unless-stopped
    container_name: redmine-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - redmine-mysql-files:/var/lib/mysql

  mongo:
    image: mongo:3.4.7
    container_name: mongo
    command: --smallfiles --setParameter failIndexKeyTooLong=false
    restart: unless-stopped
    volumes:
      - mongo-dbdata:/data/db
      - mongo-configdata:/data/configdb
    logging:
      driver: json-file
      options:
        max-size: "512m"
        max-file: "3"

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "512m"
        max-file: "3"
    ports:
      - 80:80
      - 443:443
      - 27017:27017
    volumes:
      - nginx-conf:/etc/nginx

volumes:
  redmine-files:
    external: true
  redmine-mysql-files:
    external: true
  mongo-dbdata:
    external: true
  mongo-configdata:
    external: true
  nginx-conf:
    external: true